# Generated by Django 5.0 on 2023-12-30 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardFunction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('function', models.CharField(max_length=100, verbose_name='Функция')),
            ],
            options={
                'verbose_name': 'функцию карты',
                'verbose_name_plural': 'Функции карт',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Пароль')),
                ('maxPlayers', models.SmallIntegerField(verbose_name='Максимум игроков')),
            ],
            options={
                'verbose_name': 'игру',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='Название')),
                ('descriptin', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('maxPlayerInGame', models.IntegerField(default=0, verbose_name='Максиьальное число игрков')),
                ('maxCardInColoda', models.IntegerField(default=0, verbose_name='Максиьальное число карт в колоде')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cardfunction', verbose_name='Функция')),
            ],
            options={
                'verbose_name': 'карту',
                'verbose_name_plural': 'Карты',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('position', models.SmallIntegerField()),
                ('gameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.game')),
            ],
        ),
    ]
