# Generated by Django 5.0 on 2023-12-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'игрока', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
