# Generated by Django 5.0 on 2023-12-31 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_player_options_alter_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Номер комнаты'),
        ),
        migrations.CreateModel(
            name='CardForPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fifth_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifth_card', to='backend.card')),
                ('first_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_card', to='backend.card')),
                ('fourth_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_card', to='backend.card')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.player')),
                ('second_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_card', to='backend.card')),
                ('third_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_card', to='backend.card')),
            ],
        ),
    ]
