# Generated by Django 5.0 on 2024-01-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_deck_remove_cardforplayer_fifth_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='maxPlayerInGame',
        ),
        migrations.AddField(
            model_name='card',
            name='minPlayerInGame',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Максиьальное число игрков'),
        ),
        migrations.AlterField(
            model_name='card',
            name='maxCardInColoda',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Максиьальное число карт в колоде'),
        ),
    ]
