# Generated by Django 5.0 on 2024-01-01 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_card_maxplayeringame_card_minplayeringame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='gameID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='maxCardInColoda',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Максимальное число карт в колоде'),
        ),
        migrations.AlterField(
            model_name='card',
            name='minPlayerInGame',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Минимальное число игроков'),
        ),
    ]
