# Generated by Django 5.0 on 2024-01-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_deck_gameid_alter_card_maxcardincoloda_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardforplayer',
            old_name='player_id',
            new_name='playerID',
        ),
    ]
