# Generated by Django 5.0 on 2024-01-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_player_id_cardforplayer_playerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='function',
            field=models.CharField(max_length=100, verbose_name='Функция'),
        ),
        migrations.DeleteModel(
            name='CardFunction',
        ),
    ]
