# Generated by Django 5.0 on 2024-01-13 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_card_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='cards',
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('ACT', 'Активная'), ('DEF', 'Защитная'), ('PAN', 'Паника')], default='ACT', max_length=3, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='CardFromDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.card')),
                ('deckID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.deck')),
            ],
        ),
    ]
