# Generated by Django 5.0 on 2024-01-13 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_deck_cards_alter_card_type_cardfromdeck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardforplayer',
            name='cards',
        ),
        migrations.AddField(
            model_name='cardforplayer',
            name='cardID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='backend.card'),
            preserve_default=False,
        ),
    ]
