# Generated by Django 5.0 on 2024-01-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_rename_cardid_cardforplayer_card_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardFromDeck',
            new_name='CardOfDeck',
        ),
        migrations.RenameModel(
            old_name='CardForPlayer',
            new_name='CardOfPlayer',
        ),
    ]
