# Generated by Django 5.0 on 2024-01-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_rename_cardfromdeck_cardofdeck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_group', models.CharField(max_length=50)),
                ('channel_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('PAS', 'Пассивная'), ('ACT', 'Активная'), ('DEF', 'Защитная'), ('PAN', 'Паника')], default='ACT', max_length=3, verbose_name='Тип'),
        ),
    ]
