# Generated by Django 5.0 on 2024-01-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_channels_alter_card_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channels',
        ),
    ]
